import type { Metadata } from "next";
import GallerySidebar from "@/components/gallery/GallerySidebar";
import GalleryMobileNav from "@/components/gallery/GalleryMobileNav";

export const metadata: Metadata = {
  title: "AI Gallery",
  description: "Generated by TSY AI Studio",
};

export default function GalleryLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="flex flex-row">
      <GallerySidebar />
      <GalleryMobileNav />
      {children}
    </main>
  );
}