import type { Metadata } from "next";
import GallerySidebar from "@/components/gallery/GallerySidebar";
import GalleryMobileNav from "@/components/gallery/GalleryMobileNav";
import { Toaster } from '@/components/ui/toaster'

export const metadata: Metadata = {
  title: "AI Gallery",
  description: "Generated by TSY AI Studio",
};

export default function GalleryLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex min-h-screen w-full flex-col lg:flex-row">
      <GallerySidebar />
      <GalleryMobileNav />
      <div className="mt-16 flex-1 overflow-auto py-8 lg:mt-0 lg:max-h-screen lg:py-10">
        <div className="max-w-5xl px-5 md:px-10 w-full">
          {children}
        </div>
      </div>
      <Toaster />
    </div>
  );
}